// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geektime_homework/forth/configs"
	"geektime_homework/forth/internal/biz"
	"geektime_homework/forth/internal/data"
	"geektime_homework/forth/internal/server"
	"geektime_homework/forth/internal/service"
	"geektime_homework/forth/pkg/app"
)

// Injectors from wire.go:

func initApp(conf *configs.Conf) (*app.App, error) {
	userRepo := data.NewUserRepoInMemory()
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGrpcServer(conf, userService)
	httpServer := server.NewHTTPServer(conf, userService)
	appApp := newApp(grpcServer, httpServer)
	return appApp, nil
}
